export const TEMPLATES = [
  {
    key: 'classic',
    name: 'Classic',
    icon: '📄',
    desc: 'Single-column, clean ATS-friendly design. Best for corporate, finance, and traditional roles.',
    tags: ['ATS-Safe', 'Single Column', 'Professional'],
    colorScheme: 'blue',
  },
  {
    key: 'modern',
    name: 'Modern',
    icon: '✨',
    desc: 'Two-column design with sidebar. Best for tech, creative, and design-forward roles.',
    tags: ['Modern', 'Two Column', 'Visual'],
    colorScheme: 'blue',
  },
  {
    key: 'minimal',
    name: 'Minimal',
    icon: '⬜',
    desc: 'Ultra-clean layout with minimal styling. Perfect for academic and research roles.',
    tags: ['Minimal', 'Clean', 'ATS-Safe'],
    colorScheme: 'slate',
  },
  {
    key: 'elegant',
    name: 'Elegant',
    icon: '💎',
    desc: 'Sophisticated design with elegant typography. Great for executive and senior roles.',
    tags: ['Elegant', 'Executive', 'Professional'],
    colorScheme: 'violet',
  },
  {
    key: 'executive',
    name: 'Executive',
    icon: '🏆',
    desc: 'Bold sidebar layout with professional dark accent. Ideal for leadership roles.',
    tags: ['Bold', 'Sidebar', 'Leadership'],
    colorScheme: 'emerald',
  },
  {
    key: 'creative',
    name: 'Creative',
    icon: '🎨',
    desc: 'Vibrant two-column design for creative professionals in design, media, and marketing.',
    tags: ['Creative', 'Vibrant', 'Design'],
    colorScheme: 'rose',
  },
]